[package]
name = "file_http_server"
version = "0.1.0"
authors = ["Jordi Polo Carres <jcarres@mdsol.com>"]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper", branch = "master" }
futures = "0.1.11"
mime_guess = "1.8"

